### PR TITLE
form elements #230

### LINKED ISSUE #230: Add basic form elements to UI Components
Show the following basic form elements styled in the styleguide. For remaining elements, reference the right page on the bootstrap site.
- [ ] Text input (including label styles)
- [ ] Select Dropdown
- [ ] Check Box
- [ ] Radio Button
- [ ] Submit Button (attached to input)
- [ ] Submit Button (free floating)
- [ ] Toggle
- [ ] Slider

### PR DESCRIPTION
**Pull request by binx**
closes #230 
- [x] fix form styles for IE
- [x] add outline back in for accessibility

### CODE REVIEW

**Comment by migurski** [comment]
Before we merge this, can I use this PR to show you how to preview Styleguide changes using Precog?

**Comment by migurski** [comment]
Copy-pasted from Slack:

> So, I would’ve used the branch name, but Precog is still dumb about Waffle hashes in branch names.
> 
> Meanwhile in the mapzen/website repo, I have made a new branch that points to your work in Precog, just like it’s a normal .css file. Diff is here: https://github.com/mapzen/website/commit/cb99039ffd832537210ded49defefcd46d2df3d8
> 
> Nice production URLs like `https://mapzen.com/common/styleguide/styles/blog.css` got changed to `https://precog.mapzen.com/mapzen/styleguide/19e7d20c9/styles/blog.css?go=👌`
> 
> You can see it in action by following the branch name link from here: https://precog.mapzen.com/mapzen/website/
> 
> …to here: https://precog.mapzen.com/mapzen/website/migurski/test-new-styleguide-forms/newsletter-signup
> 
> The `?ok=👌` bit is a Precog trick; normally Precog has to do a bunch of secret arithmetic to figure handle absolute links on websites by looking at referrers; this tells it to ignore all that and just use the link as-is instead of guessing about what it might have meant.
> 
> So now, you can (for example) tweak the newsletter signup form on this branch to test the new styleguide form features: https://github.com/mapzen/website/tree/migurski/test-new-styleguide-forms
> 
> And when it works and looks good, then you’ll know that the styleguide is going to have the intended effect

**Comment by hanbyul-here** [comment]
Some forms look broken on IE (I only tested 11, but it would be nice to go down to 10, we don't have list of browsers to support yet, but I think IE11 is recent enough to take some efforts.) attached the image. (tested with Browserstack) 

Forms look great on recentest Chrome& ff& Safari! 
1.One thing is that this colored checkboxes look awesome on our styleguide, but styleguide color is not really main color of Mapzen. (how do you think @souperneon ?) 
2. Also we are trying to use more svgs than png/jpg. ( There are lurking jpg,png assets.. mainly my fault.) 
1+2. It would be really nice if we have flexibility to control colors without editing image assets using [this kind of trick](http://codepen.io/noahblon/post/coloring-svgs-in-css-background-images) ?? This is a suggestion.

Let's not disable outline for any kind of input, it decreases accessibility. (Our rule is users should be able to navigate everything with keyboard in the page, I will write this on documentation.) 

I am not very sure about using word of 'submit' for search box, but maybe I am too familiar with geo-related search box. @souperneon must be better person about this. 

screen shot 2016-05-12 at 1 38 42 pm

**Comment by binx** [comment]
0) Do we have a shared browserstack account that I could use for IE testing?
1) Would love to discuss standards for colors. There are some guidelines of what the colors are used for on the documentation, but it seems like there are more unspoken assumptions.
2) Happy to switch over to SVG, should we even condense more of the assets to a single spritesheet?
3) Good call on the outline
4) Is there a different word that we use than "submit"?

**Comment by migurski** [comment]
I’ve set up a Browserstack account billed to my credit card. I created a "Mapzen" org and invited Rachel to this account—I _believe_ this means that you should be able to use unlimited session minutes billed to me for checking with Windows browsers. We will find out soon.

**Comment by hanbyul-here** [comment]
2) yas.. aggreagating all form-related assets to one sprite will make sense. 
4) surprisingly, there is no search box with any kind of button on mapzen.com yet! maybe it doesn't matter since it can be customized + there is one search bar without button ?

**Comment by migurski** [comment]
We have an immediate need for a search box for the blog that @nvkelso has raised in https://github.com/mapzen/website/issues/1002. I suggest that we approach the question of design for such an element by answering that issue.

**Comment by migurski** [comment]
I’m going to go ahead and merge this. Rhonda and I would like to use the new search box markup for Docs and Blog search boxes as soon as possible.

**Comment by souperneon** [comment]
@binx @hanbyul-here let's hangout and chat more about this before our standup? I'll send an invite

**Comment by hanbyul-here** [comment]
I will make seperate issues about svg assign @binx

**Pull request merged**
