### PR TITLE
wrapping unordered list style with text-content wrapper style

### LINKED ISSUE #62: documentation links too low on /developers
image

### PR DESCRIPTION
**Pull request by hanbyul-here**
- wrapping unordered style with `.text-content` class, this will be our class targeting static content @sleepylemur @louh @souperneon @migurski 
  closes https://github.com/mapzen/styleguide/issues/62, https://github.com/mapzen/styleguide/issues/63
- and I got rid of some elements from `index.html`, I thought it is better to leave styleguide clean, and clear about each elements, maybe we can use example page to show combination.

### CODE REVIEW

**Comment by migurski** [comment]
Regarding `.text-content`, do we have opinions about HTML5 elements like `main` that might mean the same thing?

**Comment by hanbyul-here** [comment]
:+1:  I think using `<main>`  will be simpler

**Comment by louh** [comment]
My take on it is that `<main>` is pretty agnostic about the kind of content that's inside of it, some of which could be pretty fancy (e.g. team portraits, the blurbs for projects etc). I think when we wanted to wrap things with `.text-content` it's meant to capture longer-form text documents, usually converted straight from Markdown.

I think `article` is closer semantically if we want to adopt this strategy. We don't use a lot of `<article>` that I can remember.

**Comment by migurski** [comment]
Hm good point. Maybe `<main>` is really the same as our current `div.container` , and `<article>` is `.text-content`?

**Comment by migurski** [comment]
Don’t mean to derail btw; changing how markup works isn’t supposed to be in-scope for this two week project.

**Comment by hanbyul-here** [comment]
I think `main` is more `static-content` class that we have (`container`). `article` is more about component. but since we are going to wrap each element with the tag, `article` will make more sense as @louh says

**Pull request merged**
