### PR TITLE
Update body font to Open Sans

### PR DESCRIPTION
**Pull request by rfriberg**
Closes https://github.com/mapzen/website/issues/1459

### CODE REVIEW

**Comment by souperneon** [comment]
@rfriberg can we push this to dev to QA a little more?

**Comment by rfriberg** [comment]
Totally.

FYI - @hanbyul-here, I just watered staging with updates from master.  Will merge this into staging to allow for QA on dev. 

QA/design discussion should continue on https://github.com/mapzen/website/issues/1459

**Comment by hanbyul-here** [comment]
Hey I got your concern about Poppin to be pretty wide. I also want to mention that it was good to have one font for general maintenance (We need to have a concept for body fonts/ and strong standard about when to use it if we are going to have more than one font), branding purpose (changing body font gives the most noticeably different look) .

**Comment by souperneon** [comment]
Interesting point @hanbyul-here and totally understand it is cleaner to have one typeface. But having at least 2 is common and actually great to make sure you can have some fun with headings but make sure paragraphs are readable. Poppins os unfortunately not great for reading long form text but the good thing is it works well with Open Sans is one of most highly used typeface for paragraph text these days. We should be only using Open Sans in weight 400 for the most part.

**Pull request merged**
