### PR TITLE
not activating copy button if browser doesn't support it

### LINKED ISSUE #163: “Copy Failed” when trying to use copy button
Safari 9.0.2, looks like:

copy

### PR DESCRIPTION
**Pull request by hanbyul-here**
- not activating copy button when browser doesn't support execCommand('copy') 
- closes #163

### CODE REVIEW

**Comment by louh** [comment]
@hanbyul-here I have trouble verifying this, let's walk through this together

**Comment by hanbyul-here** [comment]
@louh ok so this exec command must be run in a user-initiated callback :cry: I can't think of any smarter way to tell the browser supporting execCommand('copy'), so it detects Safari exclusively now

**Comment by hanbyul-here** [comment]
console => :cry: 
I've been meaning to resolve tab/space, then git is excited to find changes and add all lines to diffs. it is good time to do it since it is mentioned, I will resolve it with all spaces.

**Comment by louh** [comment]
:100:

**Pull request merged**
