### PR TITLE
Add scarlet contour background images at different sizes

### PR DESCRIPTION
**Pull request by louh**

### CODE REVIEW

**Comment by hanbyul-here** [comment]
This PR looks good. but probably it would be better to make all contour images follow same rule? (I put original image (not compressed- for reference purpose), large screen background image, and sm screen background image ) I did not feel much need to have xs-image, but also not feel against it. == I am fine with either way.

**Comment by louh** [comment]
Good comment - I meant to explain why I made some diversions from the rules (and maybe set forth ideas for revising the rules).

On original, "reference" assets: I think we really only should be serving compressed images in production. We shouldn't ever be in the situation where we to need to serve the uncompressed assets in production, so I'd like to have these actually live elsewhere and not in `/dist/images/`. If we keep it in the repository, putting them in `/src/` makes more sense. We're compressing images manually now, but if we were ever to move to an automated process, we can then automatically go from `/src/` -> `/dist/`.

As a result, if we leave uncompressed images out of `/dist/`, then we don't need to suffix the images with `-compressed`. (We're only suffixing the large images, anyway; does this mean the small images are not compressed? That's why we should just assume _all_ images in `dist/` are compressed. (or intend to be compressed.)

One other thing I did differently was to create one for `xs` sizes - that is, anything below 450px. The reason why is because between 450-768px is actually a really large amount of area. Below 450px wide is where the phones live -- the devices most likely to be byte-sensitive. With a file size difference of 50% I thought it would be worthwhile to have a third tier of even smaller backgrounds.

What do you think?

**Comment by hanbyul-here** [comment]
👍 for moving original images to `src` we probably have to restructure the folders so  people can clearly know which one is for images coverted into datauri and  which one is for background images. 

I think I asked opinions about 'what is the desirable size of file on mobile in this era'. I still don't have an answer for that... 🤔 However, handling more cases is def good gesture. It would be ideal if we have automatic way of generating the images but it shouldn't be a blocker. Can you handle footer background images and purple contour images too? (Which is named as an index background image? We should change this into purple-contour or something like that.)

**Comment by louh** [comment]
How are images converted to data-uri now? I couldn't find an automated process? If I put images in `src/image-assets/`, does this affect the build?

I think I didn't have a good answer for "desirable file size" because I'd never seen a rule of thumb for this. But I realized I was thinking about this phrase wrong -- it's not about any individual file, but rather the "page weight" in total. I just looked at this tool: https://pageweight.imgix.com/jobs/de2a6634-614b-47be-bf8f-71308b8c788e.html

Which says our home page is currently sitting at 4+MB with 3.83MB of that being images (and if we optimized, we could potentially bring it down by 87% -- which seems unrealistic, but I appreciate the point it's making). [This article](https://www.soasta.com/blog/page-bloat-average-web-page-2-mb/) predicts (in 2015) that average page sizes would hit 3MB by late 2017 by extrapolating from data -- which means we're already much greater than average. Not good. It then says that ideally our cap should be 1MB per page.

There's some interesting links there to articles about [performance budget](https://timkadlec.com/2013/01/setting-a-performance-budget/). I haven't looked at other sources beyond this to see if people agree or disagree, but it seems the idea behind a "budget" is that we ought to determine what we're comfortable with and stick to it.

Anyway. Yes, I will rename the other background files, and set them to behave the same way.

**Comment by hanbyul-here** [comment]
datauri is currently hand crafted. so no worry (HAHA) 

wow we do have not small page weight! Thanks for looking into it. Looking back at one image occupying more than half usage of our bucket.. we probably have to revisit the process of optimizing image. Let it not block our current flow though.

Thanks for doing image works!

**Comment by louh** [comment]
@hanbyul-here ready to go!

**Review by hanbyul-here — APPROVED** [review]

**Pull request merged**
