### PR TITLE
giving more height to docs hitbox

### PR DESCRIPTION
**Pull request by hanbyul-here**
- This was the easiest solution that I can think of
- closing https://github.com/mapzen/styleguide/issues/214

### CODE REVIEW

**Comment by louh** [comment]
Yeah - it's easy and it works, but I'm more interested in whether you can solve for the button height collapsing. Maybe flexbox is not the right answer for the doc-hitbox? Did we only do it for vertical centering (which is not even that noticeable)?

**Comment by hanbyul-here** [comment]
I see your point, but isn't height icrement anyway needed  for elements even if we could verically center elements? you mean you want those changes to be in tis pr too?

**Comment by hanbyul-here** [comment]
I am not 100% sure, based on brief inspection,  flexbox display seems to squeeze the elements when there is not enough space. The only experiments that worked is giving height to each button (which is actually span on the page btw) do you have any more suggestion?

**Comment by louh** [comment]
Yeah - flexbox is squeezing the button, which is not that helpful. I'm curious if flexbox is even necessary, though. Or maybe if the buttons and the title & text could be wrapped in elements that guaranteed a minimum height.

Anyway I'll approve the merge so you can move on but I think there are solutions that don't involve adjusting the height. When you have smaller windows (like laptop monitors) the stuff we have on our website looks way too big.

**Comment by hanbyul-here** [comment]
yes having actual content's height would be ideal. We probably need to edit DOM to actually change the height of contents, and maybe docs index page itself, which will be a lot bigger thing than this one. I am not sure where to put this further issue.(styleguide? or docs-generator?) feel free to put this as further imporvement where you think right place.

**Pull request merged**
