### PR TITLE
[FF] footer updates

### PR DESCRIPTION
**Pull request by rfriberg**
This is the styleguide component of https://github.com/mapzen/website/issues/1406

### CODE REVIEW

**Comment by souperneon** [comment]
The footer is showing the old logo for some reason? and the incorrect button style…

**Comment by rfriberg** [comment]
@souperneon where are you seeing the old logo and button style?  I'm not seeing it.

Oh, are you talking about the styleguide itself?  https://precog.mapzen.com/mapzen/styleguide/rfriberg/ff-footer-updates/  ~~It looks like it's showing a cached version of the website footer.~~  Nope. It's showing it's own footer.  Anyone know why there is a second but nearly identical footer set up for the styleguide?

**Comment by rfriberg** [comment]
On that note, we should make sure to update https://mapzen.com/common/styleguide/images/mapzen-logo-icon@2x.png with the new logo so any references that exist in the wild are updated as well.

**Comment by souperneon** [comment]
It disappeared now! Caching? 🤔 
Can I merge?
Re: 2x icon, we can remove that I think. Don't think it gets used anywhere else. We should try adding/using all assets from styleguide only.

**Comment by rfriberg** [comment]
Not caching--I updated the footer that the styleguide uses.   Yes, we can merge.

That 2x icon is in the styleguide along with a few others: https://github.com/mapzen/styleguide/tree/master/dist/images  

There are a smattering of references to that icon in the styleguide, but we can weed those out as we update those pages.  If you think that's the only place it's used, then I'm ok just removing. But we should still update https://github.com/mapzen/styleguide/blob/master/dist/images/mapzen-logo-stacked.png  I know other sites are/were using that very recently (e.g., Mobility Explorer).

**Comment by souperneon** [comment]
I would like to move "Developers" on top of the right column on mobile if possible. It's an important section and it's getting buried too low under products and data. @rfriberg is that possible?

**Comment by rfriberg** [comment]
I *think* so.  I'll look into it.

**Comment by rfriberg** [comment]
I reversed the columns to get Developers to the top, which affected the overall centering. :/ Bootstrap just does not handle five-column layouts very well.  

Here's the side-by-side of the two layouts. The bottom one has Developers pulled to the top for mobile:  https://precog.mapzen.com/mapzen/website/rfriberg/ff-footer-updates/

**Comment by souperneon** [comment]
It looks a _little_ odd but I'm good with it if you are. I imagine more things will get added to the developer section with billing and such

**Comment by rfriberg** [comment]
Yeah, as long as you're OK with the centering.  Pushing the update now.

**Review by hanbyul-here — APPROVED** [review]

**Pull request merged**
