### PR TITLE
Remove global-nav.html

### LINKED ISSUE #473: Remove site/fragments/global-nav and global-footer?
They don't seem to be used anymore, but we should make sure

### PR DESCRIPTION
**Pull request by louh**
Resolves #473.

### CODE REVIEW

**Comment by hanbyul-here** [comment]
I think it is a good idea to offer global nav and footer through styleguide eventually. but currently they are both powered by Mapzen website. Styleguide having it does make some confusions so I will give 👍

**Review by hanbyul-here — APPROVED** [review]

**Comment by louh** [comment]
Wait - is the plan to actually migrate nav and footer to styleguide? I thought we tried to do that already, (documentation used to pull nav/footer from here, I think) and ended up making repo-specific navs and footers in the end. Do we want to make a point of reversing that?

**Comment by hanbyul-here** [comment]
Developer dashboard has its own header (and I think our ideal plan is making the repo to pull the nav from somewhere central) Documentation & Metroextract is pulling the nav from the website. So I thought this pr was about making that central point to website?

**Comment by louh** [comment]
No, this PR was just to remove files that are not being used.
If we want styleguide to be the central location, then I would make another
issue that sets into motion moving the files off the website repo. (Or does
that already exist?)

**Comment by hanbyul-here** [comment]
In my mind, 'making website as a central point' includes 'removing not-used files styleguide' (so it is obvious for everybody that nav in styleguide is not used, and the website is where other repos pull the nav from). Yeah as you said, I don't see now as a timing of changing from where other repos are pulling nav. I left the first comment since I think it makes more sense that styleguide lives with global nav and footer since the styleguide controls how it looks eventually? However, this global nav confused us where other repos are pulling their navs from, so I find the nav in this repo ok to go away for now.

**Pull request merged**
