### PR TITLE
adding grids to design elements

### LINKED ISSUE #227: Grid system used on the website
Show the grid structure the website is using and add examples of different screen sizes for those grids

### PR DESCRIPTION
**Pull request by souperneon**
added a blurb about grids to /design-elements
closes https://github.com/mapzen/styleguide/issues/227 and  https://github.com/mapzen/styleguide/issues/231

### CODE REVIEW

**Comment by souperneon** [comment]
not sure that is enough info about media queries? @binx @hanbyul-here feel free to add…

**Comment by hanbyul-here** [comment]
I think media query can go bottom of the grid part, and maybe don't have to show default values since we are just using 12 grid columns that you linked. maybe we can add we set max-width for container in mapzen.com / and each brewk point for small screen and mobile.

**Comment by souperneon** [comment]
@hanbyul-here that sounds like it will make things easier, when they are making new pages. Is that the best way?

I'll remove the default values.
Do we need more about media queries?

**Comment by hanbyul-here** [comment]
we actually are using just default value for containers, so we probably don't have to say it again on our styleguide page (sorry I thought we are overriding the value, but we are doing it only for blog post, so probably doesn't need to be mentioned) media queries too, sorry about hassle!

**Comment by binx** [comment]
Do we want to mention any other layouts than the one-column .container div? Or at least say how people could make, say, a 2-column layout? 
I really like the Introduction and Example sections on http://getbootstrap.com/css/#grid

**Comment by hanbyul-here** [comment]
I really like Bootstrap page too! As much I like it, I am not sure we have to do duplicate work of bootstrap, I'd rather guide people to Bootstrap site. (or you mean we should put links for http://getbootstrap.com/css/#grid ? @binx ?) 
If it scares people to go to Bootstrap site, I don't mind putting some example layers either.

**Comment by hanbyul-here** [comment]
I put my suggestion in this pr https://github.com/mapzen/styleguide/pull/244

**Comment by souperneon** [comment]
@hanbyul-here check it out now

**Comment by hanbyul-here** [comment]
for container: there is more option than `container` to use grids,  `container-fluid` wrapper, which expands to full width of viewport. this is why I mentioned max-width with `container` class on pr.  I think this information is worth exposed somehow?

**Comment by souperneon** [comment]
those are the only two options right? 
We should mention both of those and specifically what they do

**Comment by hanbyul-here** [comment]
`p` tag wrapping text will be helpful since p can give some padding when grids collapse, and maybe put different content than `p` not to give impression that `p` is required. I can push change if you don't mind! @souperneon ?

**Comment by souperneon** [comment]
do it!! @hanbyul-here

**Pull request merged**
