### PR TITLE
[DO NOT MERGE] Replace favicon with new logo (experimental)

### PR DESCRIPTION
**Pull request by louh**
Check it out: https://precog.mapzen.com/mapzen/styleguide/lou/favicon/samples/projects-tangram.html

One of my concerns with the new logo is that it gets very muddy when it is scaled down. This is extremely evident when it's used as a favicon, as in the sample link above.

In other words, don't merge this because this is not going to work out. Some possible recommendations (not mutually exclusive):

1. Revise the logo with scaled-down situations in mind.
2. Draw a new, simpler version of the logo that works at this scale.
3. Manually paint-by-pixel instead of using automated scaling algorithms.

### CODE REVIEW

**Comment by rfriberg** [comment]
I played with favicons a little... 
https://precog.mapzen.com/mapzen/styleguide/rfriberg/staging/favicon/samples/projects-tangram.html
https://precog.mapzen.com/mapzen/styleguide/rfriberg/staging/favicon2/samples/projects-tangram.html

Eh, we probably need @souperneon's help.

**Comment by souperneon** [comment]
Latest here - https://precog.mapzen.com/mapzen/styleguide/staging/samples/blog-main.html
Good to go!

**Comment by souperneon** [comment]
Can we close this PR now?

**Comment by louh** [comment]
let's close it

**Pull request closed without merging**
